### PR TITLE
Dependent mapping js

### PR DESCRIPTION
**Pull request by derins**
# Current issues
1. No unittests for json2png
2. png file does not download but display on the screen
3. user input is always assumed to be optional (not an issue if it's always optional)

# Code changes
1. dependent mapping dict passed to layout.html
2. json is stored as string and parsed to run as a js object
3. convert.js updated with jquery to dynamically generate the user input field when converter asks

# Documentation changes
none

# Validation suggestions
1. Set up the environment using commands in README.md
2. run 
```
python app.py
```
3. go to localhost:5000 on browser
4. go to convert tab and upload json file from test_files folder
5. select png as convertTo option
6. add custom options to any textbox - or leave them empty

### CODE REVIEW

**Comment by jongoncalves** [comment]
@derins you are jumping the gun again. This PR regresses a few issues the previous PR just fixed. Please close this PR, merge master into this branch and re-open the PR. As it stands it contains conflicts and problems.

**Comment by derins** [comment]
Got it

**Comment by jongoncalves** [comment]
Looks like you aren't using ajax for this which is causing all this weird JSON manipulation. For now it's ok - we gotta context switch to DEVINE. We'll get back to improvements here later.

**Review by jongoncalves — APPROVED** [review]

**Comment by derins** [comment]
I'll add that to the to-do list

**Pull request merged**
